version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 433:433
      - 80:80
    volumes:  
      - /etc/letsencrypt:/etc/letsencrypt:ro  
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    

