version: '3'
services:
  app:
    image: "mikkelij88/dgr_app:latest"
    ports:
      - 443:443
      - 80:80
    volumes:  
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
