version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    volumes:  
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']